version: '3.9'

services:
  web:
    build: .
    container_name: drf_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DEBUG: 1
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: drf_db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: drf_db
      POSTGRES_USER: drf_user
      POSTGRES_PASSWORD: drf_pass

volumes:
  pgdata:
